version: "3.4"

services:
    proxy:
        build: ./docker/proxy
        container_name: blood-pressure-reverse-proxy
        ports:
            - "80:80"
        volumes:
            - ./docker/proxy/server.conf/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - app
    db:
        build: ./docker/db
        container_name: blood-pressure-db
        environment: 
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
            PGPASSWORD: "password"
            POSTGRES_DB: "bloodpressure"
            DATABASE_HOST: "localhost"
            POSTGRES_INITDB_ARGS:  "--encoding=UTF-8 --locale=ja_JP.UTF-8"
        tty: true
        stdin_open: true
        ports:
            - "35432:5432"
        expose:
            - "5432"
        #volumes: 
        #    - ./docker/db/data:/var/lib/postgresql/data
        #    - ./docker/db/postgres_data:/postgres_data
    app:
        build: ./spring-blood-pressure
        container_name: spring-blood-pressure-app
        expose:
            - "8082"
        depends_on: 
            - db
        volumes: 
            - ./spring-blood-pressure:/app
            - ./docker/app/log:/var/log/app
    client:
        build: ./client-blood-pressure
        container_name: client-blood-pressure-app
        ports:
            - "8080:8080"
        expose:
            - "8080"
        volumes:
            - ./client-blood-pressure:/app
        tty: true
        stdin_open: true